### ISSUE TITLE
0.00 HashRate for NVIDIA GPUs (1060 6GB and 1070) on Ubuntu Linux 16 Cuda 10 zilminer v0.1.25

### ISSUE THREAD

**Issue by wargun02** [DurianStallSingapore/ZILMiner#12]
**Describe the bug**
My GPUs shows 0.00 h all the while. Running Ubuntu Linux 16 with proper nvidia drivers and CUDA 10 installed. Running zilminer v0.1.25

The log which I have gotten:
zilminer 0.1.25-1+commit.4f9884d0
Build: linux/release/gnu

^[[94m i ^[[35m12:31:03 ^[[94mzilminer ^[[0mConfigured pool pool.zil.farm:5000
^[[94m i ^[[35m12:31:03 ^[[94mzilminer ^[[0mSelected pool pool.zil.farm:5000
^[[94m i ^[[35m12:31:03 ^[[94mzilminer ^[[0mEstablished connection to pool.zil.farm [104.200.24.75:5000]
^[[94m i ^[[35m12:31:03 ^[[94mzilminer ^[[0mSpinning up miners...
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-0   ^[[0mUsing Pci Id : 01:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-1   ^[[0mUsing Pci Id : 02:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-2   ^[[0mUsing Pci Id : 03:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-3   ^[[0mUsing Pci Id : 04:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-4   ^[[0mUsing Pci Id : 05:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-5   ^[[0mUsing Pci Id : 07:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-6   ^[[0mUsing Pci Id : 08:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-7   ^[[0mUsing Pci Id : 09:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-8   ^[[0mUsing Pci Id : 0a:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-9   ^[[0mUsing Pci Id : 0b:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-10  ^[[0mUsing Pci Id : 0c:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[33mcu ^[[35m12:31:03 ^[[94mcuda-11  ^[[0mUsing Pci Id : 0d:00.0 GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
^[[32m m ^[[35m12:31:13 ^[[94mzilminer ^[[0m^[[32m0:00^[[0m^[[1;97m A0^[[0m ^[[1;36m0.00 h^[[0m - cu0 ^[[36m0.00^[[0m, cu1 ^[[36m0.00^[[0m, cu2 ^[[36m0.00^[[0m, cu3 ^[[36m0.00^[[0m, cu4 ^[[36m0.00^[[0m, cu5 ^[[36m0.00^[[0m, cu6 ^[[36m0.00^[[0m, cu7 ^[[36m0.00^[[0m, cu8 ^[[36m0.00^[[0m, cu9 ^[[36m0.00^[[0m, cu10 ^[[36m0.00^[[0m, cu11 ^[[36m0.00^[[0m
^[[32m m ^[[35m12:31:23 ^[[94mzilminer ^[[0m^[[32m0:00^[[0m^[[1;97m A0^[[0m ^[[1;36m0.00 h^[[0m - cu0 ^[[36m0.00^[[0m, cu1 ^[[36m0.00^[[0m, cu2 ^[[36m0.00^[[0m, cu3 ^[[36m0.00^[[0m, cu4 ^[[36m0.00^[[0m, cu5 ^[[36m0.00^[[0m, cu6 ^[[36m0.00^[[0m, cu7 ^[[36m0.00^[[0m, cu8 ^[[36m0.00^[[0m, cu9 ^[[36m0.00^[[0m, cu10 ^[[36m0.00^[[0m, cu11 ^[[36m0.00^[[0m
^[[32m m ^[[35m12:31:33 ^[[94mzilminer ^[[0m^[[32m0:00^[[0m^[[1;97m A0^[[0m ^[[1;36m0.00 h^[[0m - cu0 ^[[36m0.00^[[0m, cu1 ^[[36m0.00^[[0m, cu2 ^[[36m0.00^[[0m, cu3 ^[[36m0.00^[[0m, cu4 ^[[36m0.00^[[0m, cu5 ^[[36m0.00^[[0m, cu6 ^[[36m0.00^[[0m, cu7 ^[[36m0.00^[[0m, cu8 ^[[36m0.00^[[0m, cu9 ^[[36m0.00^[[0m, cu10 ^[[36m0.00^[[0m, cu11 ^[[36m0.00^[[0m
^[[32m m ^[[35m12:31:43 ^[[94mzilminer ^[[0m^[[32m0:00^[[0m^[[1;97m A0^[[0m ^[[1;36m0.00 h^[[0m - cu0 ^[[36m0.00^[[0m, cu1 ^[[36m0.00^[[0m, cu2 ^[[36m0.00^[[0m, cu3 ^[[36m0.00^[[0m, cu4 ^[[36m0.00^[[0m, cu5 ^[[36m0.00^[[0m, cu6 ^[[36m0.00^[[0m, cu7 ^[[36m0.00^[[0m, cu8 ^[[36m0.00^[[0m, cu9 ^[[36m0.00^[[0m, cu10 ^[[36m0.00^[[0m, cu11 ^[[36m0.00^[[0m
^[[32m m ^[[35m12:31:53 ^[[94mzilminer ^[[0m^[[32m0:00^[[0m^[[1;97m A0^[[0m ^[[1;36m0.00 h^[[0m - cu0 ^[[36m0.00^[[0m, cu1 ^[[36m0.00^[[0m, cu2 ^[[36m0.00^[[0m, cu3 ^[[36m0.00^[[0m, cu4 ^[[36m0.00^[[0m, cu5 ^[[36m0.00^[[0m, cu6 ^[[36m0.00^[[0m, cu7 ^[[36m0.00^[[0m, cu8 ^[[36m0.00^[[0m, cu9 ^[[36m0.00^[[0m, cu10 ^[[36m0.00^[[0m, cu11 ^[[36m0.00^[[0m
^[[32m m ^[[35m12:32:03 ^[[94mzilminer ^[[0m^[[32m0:01^[[0m^[[1;97m A0^[[0m ^[[1;36m0.00 h^[[0m - cu0 ^[[36m0.00^[[0m, cu1 ^[[36m0.00^[[0m, cu2 ^[[36m0.00^[[0m, cu3 ^[[36m0.00^[[0m, cu4 ^[[36m0.00^[[0m, cu5 ^[[36m0.00^[[0m, cu6 ^[[36m0.00^[[0m, cu7 ^[[36m0.00^[[0m, cu8 ^[[36m0.00^[[0m, cu9 ^[[36m0.00^[[0m, cu10 ^[[36m0.00^[[0m, cu11 ^[[36m0.00^[[0m

**To Reproduce**
./zilminer -U -P zil://0xC50d4ccD441ffea071A2065A229ca4D4A03Ed82e.RIGZOTAC1060X12@pool.zil.farm:5000/api

**Environment (please complete the following information):**
- OS
Ubuntu Linux 16, Nvidia Drivers, Cuda 10

- Hardware
12 x NVIDIA 1060 6GB
6 x NVIDIA 1070

**Comment by rpirsc13** [comment]
@wargun02

It is to be expected. During bootstrap you only 'mine' at every DS epoch ( every 100 TX epoch, ~ 3 hours ). Bootstrap is expected to last for 27 more days during which there are no transactions allowed. So expected your GPUs to stay idle 99% of the time until then.

More info: https://viewblock.io/zilliqa and https://github.com/Zilliqa/Zilliqa/wiki/Mining

**Comment by wargun02** [comment]
Thanks for clarifying.
