### ISSUE TITLE
Stratum support?

### ISSUE THREAD

**Issue by 1notchdev** [DurianStallSingapore/ZILMiner#20]
Is it support for Stratum, too?

If yes, is there any guide documentation for it?

**Comment by ShengguangXiao** [comment]
We are working on it right now, it will be ready in coming 2 or 3 weeks.

**Comment by ShengguangXiao** [comment]
@1notchdev The stratum support is done already. Please follow below ethminer user manual to connect to the pool.
https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md

**Comment by 1notchdev** [comment]
@ShengguangXiao , thank you
