### ISSUE TITLE
Are all arguments needed when dual mining

### ISSUE THREAD

**Issue by Mukrosz** [DurianStallSingapore/ZILMiner#3]
Hi there,

I am doing GPU rigs to 1 CPU node using the windows zilminer 0.1.25 cuda10.
I'd like to dual mine and saw you have the arguments for start/stop.
is this what my batch file should be like?

`zilminer --pow-start stopAE.bat --pow-end startAE.bat --max-submit=1 --farm-recheck 10000 --work-timeout=7200 --farm-retries=10 --retry-delay=10 -P zil://wallet_address.worker_name@zil_node_ip:get_work_port`

Are all of these necessary?

many thanks

**Comment by ShengguangXiao** [comment]
No, only --pow-start stopAE.bat --pow-end startAE.bat -P zil://wallet_address.worker_name@zil_node_ip:get_work_port is needed

**Comment by Mukrosz** [comment]
thank you, does it hurt to have them? I just used them as per your guide's instriuctions

**Comment by ShengguangXiao** [comment]
No hurt

**Comment by Mukrosz** [comment]
thank you

**Comment by Mukrosz** [comment]
--pow-end does not seem to start my batch file that start another miner. Are there any logs I can check to see why?

--pow-start works

**Comment by Mukrosz** [comment]
Never mind, it is indeed related to when PoW is truly over which
